











































































































































































































































































































































services:
  - type: web
    name: my_flutter_app
    runtime: static
    buildCommand: bash ./build.sh
    staticPublishPath: build/web
    autoDeployTrigger: commit
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
